# Configuration for KHcompare
year:
  - 2022

win.drive:
  - "F:"
linux.drive:
  - "/mnt/F"

# Don't include the drive when specifying kube-root
kube.root:
  - "Forskningsprosjekter/PDB 2455 - Helseprofiler og til_/PRODUKSJON/PRODUKTER/KUBER"

# Folder to keep relevant files for KHompare to work
# such as population reference and database files
khompare.root:
  - "Forskningsprosjekter/PDB 2455 - Helseprofiler og til_/PRODUKSJON/VALIDERING/KHompare"

# Geo granularity. "K" is for bigger kommuner and "km" for smaller
geo.levels:
  - L
  - F
  - K
  - km
  - B

# Demographic variables
demo.vars:
  - GEO
  - AAR
  - KJONN
  - ALDER

# Measure Variables from LagKUBE function
# The variables to be compared with
kube.vars:
  - Adjusted
  - adjusted
  - ADJUSTED
  - ANT_OPPGITT
  - Ant_pers
  - ANTALL
  - antall
  - Antall_personer
  - antallaar
  - ANTLEDIGE
  - Crude
  - crude
  - DEKNINGSGRAD
  - dekningsgrad
  - E0
  - FODTE
  - folketall
  - GINI
  - LANDSNORM
  - MALTALL
  - MEDIAN_INNTEKT
  - MEDIANINNTEKT_AH
  - MEIS
  - NETTO
  - NEVNER
  - nevner
  - nevner_aarlig
  - num_femGeonivaa
  - PERSONER
  - Personer
  - personer_distribnett
  - per1000
  - PRIKK
  - PROGNOSEAAR
  - prosentandel
  - RATE
  - SMR
  - smr
  - sumnevner
  - sumNEVNER
  - SUMNEVNER
  - sumteller
  - sumTELLER
  - SUMTELLER
  - TELLER
  - teller_aarlig
  - TILVEKST
  - v6
  - v7
  - VERDI

## Misc variables to be ignored
misc.vars:
  - ekstradims
  - level
  - SPVFLAGG
  - storkommune
  - RATE.n

verbose: TRUE
