# Geo recode reference year
# To select which geo recode table to use eg. 2021 will use tables grunnkrets2021, kommune2021 etc
year: 2024

# Set encoding
encoding.access: UTF-8
encoding.csv: Latin-1

# Paths. Used to generate paths using `is_orgcube_path()`
folder.root: "O:/Prosjekt/FHP/PRODUKSJON"
# Main folders
folder.db: "STYRING"
folder.data: "ORGDATA"
folder.dumps: "RUNTIMEDUMP"
folder.filegroups: "PRODUKTER/MELLOMPROD/R/STABLAORG"
folder.kommunehelsa: "PRODUKTER/KUBER/KOMMUNEHELSA"
folder.norgeshelsa: "PRODUKTER/KUBER/NORGESHELSA"
folder.friskvikF: "PRODUKTER/KUBER/FRISKVIK_FYLKE"
folder.friskvikK: "PRODUKTER/KUBER/FRISKVIK_KOMM"
folder.friskvikB: "PRODUKTER/KUBER/FRISKVIK_BYDEL"
folder.ovpF: "PRODUKTER/KUBER/OVP_FYLKE"
folder.ovpK: "PRODUKTER/KUBER/OVP_KOMM"
folder.ovpB: "PRODUKTER/KUBER/OVP_BYDEL"
folder.buffer: file.path(fs::path_home(), "helseprofil")
# Subfolders
folder.sub.datert: "DATERT"
folder.sub.nyeste: "NYESTE"
folder.sub.QC: "QC"
folder.sub.specs: "SPECS"
# Formatfolders
folder.format.csv: "csv"
folder.format.R: "R"

# 
stataprikkfile: "BIN/Z_Statasnutter/StataPrikking.do"

# Access database file for orgdata
db: KHelsa.mdb
logg: KHlogg.mdb

# Geographical granularities
geo.levels:
  - land
  - grunnkrets
  - fylke
  - kommune
  - bydel
  - delbydel

## How many digits to represent geo codes including the leading zero
geo.digits:
  - land : 1
  - grunnkrets : 8
  - fylke : 2
  - kommune : 4
  - bydel : 6
  - delbydel : 8

# Abbreviation for geo granularities that will be used in AGGREGATE column in
# tabel FILGRUPPE in MS Access database.
geo.abv:
  - land : L
  - grunnkrets : G
  - fylke : F
  - kommune : K
  - bydel : B
  - delbydel : D

# Standard columns that will be in the output dataset whenever available in the
# original dataset
columns:
 - GEO
 - LEVEL
 - AAR
 - KJONN
 - ALDER
 - UTDANN
 - LANDSSB

# Diverse fra khglobs
kolorgs: 
 - GEO
 - AAR
 - KJONN
 - ALDER
 - UTDANN
 - INNVKAT
 - LANDBAK
 - TAB1
 - TAB2
 - TAB3
 - VAL1
 - VAL2
 - VAL3
taborgs: 
 - GEO
 - AAR
 - KJONN
 - ALDER
 - TAB1
 - TAB2
 - TAB3
NesstarOutputDef: 
  MT: "MALTALL"
  T: "TELLER"
  N: "NEVNER"
  RATE: "RATE"
  SMR: "SMR"
  MEIS: "MEIS"
  ST: "sumTELLER"
  SN: "sumNEVNER"
  SPT: "sumPREDTELLER"
  RN: "RATE.n"
FriskvikTabs: 
 - GEO 
 - AAR
 - KJONN
 - ALDER
 - UTDANN
 - INNVKAT
 - LANDBAK
 - ETAB
FriskvikVals: 
 - sumTELLER
 - sumNEVNER
 - RATE
 - MALTALL
 - sumPREDTELLER
 - PREDTELLER
 - SMR
 - NORM
 - MEIS
 - RATE.n
QCVals: 
 - TELLER
 - NEVNER
 - sumTELLER
 - sumNEVNER
 - RATE.n
geo_illeg: "GGG"
alder_illeg: "888_888"
alder_ukjent: "999_999"
kjonn_illeg: "8"
kjonn_ukjent: "9"
aar_illeg: "8888_8888"
utdann_illeg: "8"
utdann_ukjent: "9"
landbak_illeg: "8"
landbak_ukjent: "9"
innvkat_illeg: "8"
innvkat_ukjent: "9"
DefDumpFormat: "CSV"
